apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: auth-agent-injector
webhooks:
  - name: auth-agent-injector.arq-agent.io
    clientConfig:
      service:
        name: controller
        namespace: auth-agent-controller
        path: "/inject"
        port: 443
    sideEffects: None
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    reinvocationPolicy: "Never"
    admissionReviewVersions: ["v1beta1", "v1"]
    namespaceSelector:
      matchExpressions:
        - key: sidecar.arq-agent.io/inject
          operator: In
          values:
            - "true"
    objectSelector:
      matchExpressions:
        - key: sidecar.arg-agent.io/inject
          operator: NotIn
          values:
            - "false"
