# Copyright 2024 The AuthRequestAgent Authors.  All rights reserved.
# Use of this source code is governed by an Apache2
# license that can be found in the LICENSE file.

services:

  proxy:
    image: envoyproxy/envoy:v1.32-latest
    volumes:
      - type: bind
        source: ./proxy/envoy.yaml
        target: /etc/envoy.yaml
        read_only: true
    ports:
      - 80:80
    command: "--concurrency 1 --log-level debug --config-path /etc/envoy.yaml"
    depends_on:
      - agent
      - backend

  agent:
    image: ghcr.io/auth-request-agent/agent:local
    command: "run --log-check-results --tls-disable /policy.yaml"
    volumes:
      - type: bind
        source: ./agent/policy.yaml
        target: /policy.yaml
    ports:
      - 9191:9191

  backend:
    image: jmalloc/echo-server
    ports:
      - 8080:8080
